blueprint:
  name: Circadian Lighting for Light Bulbs
  description: Adjusts brightness and color temperature of light bulbs based on the elevation of the sun.
  domain: automation
  input:
    light_group:
      name: Light Group
      description: The group of light bulbs to control
      selector:
        entity:
          domain: light
          multiple: true
  variables:
    lights: !input light_group

trigger:
  - platform: time_pattern
    minutes: "/2"
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunset

variables:
  sun_elevation: "{{ state_attr('sun.sun', 'elevation') }}"
  current_time: "{{ now().strftime('%H:%M') }}"

sequence:
  - choose:
      # Daytime
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            above: 0
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_group
            data:
              brightness: "{{ (((sun_elevation | float) / 90) * 255) | round(0) }}"
              kelvin: "{{ ((((sun_elevation | float) / 90) * 4500) + 2000) | round(0) }}"
      # Night time
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 0
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_group
            data:
              brightness: "{{ [3, (((-sun_elevation | float) / 18) * 252 + 3) | round(0)] | min }}"
              kelvin: 2000
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_group
        data:
          brightness: 3
          kelvin: 2000