blueprint:
  name: Circadian Lighting for TP-Link Bulbs
  description: Adjusts brightness and color temperature of TP-Link bulbs based on sun position
  domain: automation
  input:
    light_group:
      name: Light Group
      description: The group of TP-Link lights to control
      selector:
        entity:
          domain: light
          multiple: true

variables:
  lights: !input light_group

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunset

action:
  - variables:
      sun_elevation: "{{ state_attr('sun.sun', 'elevation') }}"
  - choose:
      # Daytime
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            above: 0
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_group
            data:
              brightness: "{{ (((sun_elevation | float) / 90) * 255) | round(0) }}"
              kelvin: "{{ ((((sun_elevation | float) / 90) * 2700) + 2700) | round(0) }}"
      # Night time
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 0
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_group
            data:
              brightness: 3  # 1% of 255
              kelvin: 2700